use db_oniees_main;

SET @codigo_buscado = '00003253';

SELECT  
    e.codigo AS codigo_ipress, 
    i.nombre AS institucion, 
    e.nombre_eess, 
    r.nombre AS region, 
    p.nombre AS provincia, 
    d.nombre AS distrito, 
    e.nombre_red AS red, 
    e.nombre_microred AS microred, 
    e.nivel_atencion, 
    cat.nombre AS categoria_actual, 
    e.resolucion_categoria, 
    e.clasificacion, 
    e.tipo, 
    e.codigo_ue, 
    e.unidad_ejecutora, 
    e.director_medico, 
    e.horario, 
    e.telefono, 
    e.inicio_funcionamiento, 
    e.fecha_registro, 
    e.ultima_recategorizacion, 
    e.antiguedad_anios, 
    e.categoria_inicial, 
    e.quintil, 
    e.pcm_zona, 
    e.frontera, 
    e.numero_camas, 
    e.autoridad_sanitaria, 
    e.propietario_ruc, 
    e.propietario_razon_social, 
    e.situacion_estado, 
    e.situacion_condicion, 
    e.direccion, 
    e.referencia, 
    e.coordenada_utm_norte, 
    e.coordenada_utm_este, 
    f.seguridad_hospitalaria, 
    f.seguridad_resultado, 
    f.seguridad_fecha, 
    f.patrimonio_cultural, 
    f.fecha_emision, 
    f.numero_documento, 
    f.tipo_documento_registrador, 
    f.doc_entidad_registrador, 
    f.nombre_registrador, 
    pr.nombre AS nombre_profesion,
    f.cargo_registrador,
    cp.nombre AS condicion_profesional,
    rl.nombre AS regimen_laboral,
    f.regimen_laboral_otro,
    f.email_registrador,
    f.movil_registrador,
    
    -- DATOS DE TERRENO (format_i)
    fi.t_estado_saneado,
    fi.t_condicion_saneamiento,
    fi.t_nro_contrato,
    fi.t_titulo_a_favor,
    fi.t_observacion,
    fi.t_area_terreno,
    fi.t_area_construida,
    fi.t_area_estac,
    fi.t_area_libre,
    fi.t_estacionamiento,
    fi.t_inspeccion,
    fi.t_inspeccion_estado,
    
    -- PLANOS TECNICOS (format_i)
    fi.pf_ubicacion,
    fi.pf_estructuras,
    fi.pf_ins_mecanicas,
    fi.pf_perimetro,
    fi.pf_ins_sanitarias,
    fi.pf_ins_comunic,
    fi.pf_arquitectura,
    fi.pf_ins_electricas,
    fi.pf_distribuicion,
    fi.pd_ubicacion,
    fi.pd_perimetro,
    fi.pd_arquitectura,
    fi.pd_estructuras,
    fi.pd_ins_sanitarias,
    fi.pd_ins_electricas,
    fi.pd_ins_mecanicas,
    fi.pd_ins_comunic,
    fi.pd_distribuicion,
    
    -- ACABADOS EXTERIORES (format_i)
    fi.ae_pavimentos,
    fi.ae_pavimentos_nombre,
    fi.ae_pav_estado,
    fi.ae_veredas,
    fi.ae_veredas_nombre,
    fi.ae_ver_estado,
    fi.ae_zocalos,
    fi.ae_zocalos_nombre,
    fi.ae_zoc_estado,
    fi.ae_muros,
    fi.ae_muros_nombre,
    fi.ae_mur_estado,
    fi.ae_techo,
    fi.ae_techo_nombre,
    fi.ae_tec_estado,
    
    -- DATOS DE EDIFICACION (format_i_one)
    GROUP_CONCAT(DISTINCT fio.id SEPARATOR '; ') AS edificacion_ids,
    GROUP_CONCAT(DISTINCT fio.bloque SEPARATOR '; ') AS edificacion_bloques,
    GROUP_CONCAT(DISTINCT fio.pabellon SEPARATOR '; ') AS edificacion_pabellones,
    GROUP_CONCAT(DISTINCT fio.servicio SEPARATOR '; ') AS edificacion_servicios,
    GROUP_CONCAT(DISTINCT fio.nropisos SEPARATOR '; ') AS edificacion_nropisos,
    GROUP_CONCAT(DISTINCT fio.antiguedad SEPARATOR '; ') AS edificacion_antiguedades,
    GROUP_CONCAT(DISTINCT fio.ultima_intervencion SEPARATOR '; ') AS edificacion_ultimas_intervenciones,
    GROUP_CONCAT(DISTINCT fio.tipo_intervencion SEPARATOR '; ') AS edificacion_tipos_intervencion,
    GROUP_CONCAT(DISTINCT fio.observacion SEPARATOR '; ') AS edificacion_observaciones,
    
    -- DATOS DE ACABADOS INTERIORES (format_i_two)
    GROUP_CONCAT(DISTINCT fit.id SEPARATOR '; ') AS acabado_ids,
    GROUP_CONCAT(DISTINCT fit.pisos SEPARATOR '; ') AS acabado_pisos,
    GROUP_CONCAT(DISTINCT fit.pisos_nombre SEPARATOR '; ') AS acabado_pisos_nombres,
    GROUP_CONCAT(DISTINCT fit.pisos_estado SEPARATOR '; ') AS acabado_pisos_estados,
    GROUP_CONCAT(DISTINCT fit.veredas SEPARATOR '; ') AS acabado_veredas,
    GROUP_CONCAT(DISTINCT fit.veredas_nombre SEPARATOR '; ') AS acabado_veredas_nombres,
    GROUP_CONCAT(DISTINCT fit.veredas_estado SEPARATOR '; ') AS acabado_veredas_estados,
    GROUP_CONCAT(DISTINCT fit.zocalos SEPARATOR '; ') AS acabado_zocalos,
    GROUP_CONCAT(DISTINCT fit.zocalos_nombre SEPARATOR '; ') AS acabado_zocalos_nombres,
    GROUP_CONCAT(DISTINCT fit.zocalos_estado SEPARATOR '; ') AS acabado_zocalos_estados,
    GROUP_CONCAT(DISTINCT fit.muros SEPARATOR '; ') AS acabado_muros,
    GROUP_CONCAT(DISTINCT fit.muros_nombre SEPARATOR '; ') AS acabado_muros_nombres,
    GROUP_CONCAT(DISTINCT fit.muros_estado SEPARATOR '; ') AS acabado_muros_estados,
    GROUP_CONCAT(DISTINCT fit.techo SEPARATOR '; ') AS acabado_techos,
    GROUP_CONCAT(DISTINCT fit.techo_nombre SEPARATOR '; ') AS acabado_techos_nombres,
    GROUP_CONCAT(DISTINCT fit.techo_estado SEPARATOR '; ') AS acabado_techos_estados,
    
     -- DATOS DEL EDIFICIO (format_i) 3.1.3.1
    fi.sonatos,
    fi.pisos AS num_pisos_superiores,
    fi.area AS area_aproximada,
    fi.ubicacion AS ubicacion_ee_ss,
    fi.material AS tipo_material,
    fi.material_nombre,
    
    -- EVALUACIÓN DEL ESTADO DE LA INFRAESTRUCTURA (format_i) 3.1.3.2
    fi.infraestructura_option_a,
    fi.infraestructura_valor_a,
    fi.infraestructura_descripcion_1,
    fi.infraestructura_option_b,
    fi.infraestructura_valor_b,
    fi.infraestructura_descripcion_2,
    fi.infraestructura_option_c,
    fi.infraestructura_valor_c,
    fi.infraestructura_descripcion_3,
    fi.infraestructura_option_d,
    fi.infraestructura_valor_d,
    fi.infraestructura_option_e,
    fi.infraestructura_valor_e,
    fi.infraestructura_option_f,
    fi.infraestructura_valor_f,
    fi.infraestructura_option_g,
    fi.infraestructura_valor_g,
    fi.infraestructura_option_h,
    fi.infraestructura_valor_h,
    fi.infraestructura_option_i,
    fi.infraestructura_valor_i,
    fi.infraestructura_option_j,
    fi.infraestructura_valor_j,
    fi.infraestructura_option_k,
    fi.infraestructura_valor_k,
    fi.infraestructura_option_l,
    fi.infraestructura_valor_l,
    fi.infraestructura_option_m,
    fi.infraestructura_valor_m,
    fi.infraestructura_option_n,
    fi.infraestructura_valor_n,
    fi.infraestructura_descripcion_a,
    fi.infraestructura_descripcion_b,
    fi.infraestructura_descripcion_c,
    fi.infraestructura_descripcion_d,
    fi.infraestructura_descripcion_e,
    fi.infraestructura_descripcion_f,
    fi.infraestructura_descripcion_g,
    fi.infraestructura_descripcion_h,
    fi.infraestructura_descripcion_i,
    fi.infraestructura_descripcion_j,
    fi.infraestructura_descripcion_k,
    fi.infraestructura_descripcion_l,
    fi.infraestructura_descripcion_m,
    fi.infraestructura_descripcion_n,
    
    -- ESTADO DEL ENTORNO / CERRAMIENTO PERIMETRAL
    fi.estado_contencion,
    fi.estado_taludes,
    fi.cp_erco_perim,
    fi.cp_material,
    fi.cp_material_nombre,
    fi.cp_estado,
    
    -- OBSERVACIONES DEL EVALUADOR
    fi.observacion,
    
    -- IDENTIFICACION PRELIMINAR DE TIPO DE INTERVENCION
    fi.fecha_evaluacion,
    fi.hora_inicio,
    fi.hora_final,
   
    -- DETERMINACION DE LA OPERATIVIDAD
    fi.comentarios,
   
    -- ARCHIVOS / FOTOS (format_i_files)
    GROUP_CONCAT(DISTINCT fif.id SEPARATOR '; ') AS fotos_ids,
    GROUP_CONCAT(DISTINCT fif.nombre SEPARATOR '; ') AS fotos_nombres,
    GROUP_CONCAT(DISTINCT fif.url SEPARATOR '; ') AS fotos_urls,
    GROUP_CONCAT(DISTINCT fif.size SEPARATOR '; ') AS fotos_sizes,
    COUNT(fif.id) AS total_fotos   
   
FROM establishment e 
LEFT JOIN institucion i ON e.id_institucion = i.id 
LEFT JOIN regions r ON e.idregion = r.id 
LEFT JOIN provinces p ON e.idprovincia = p.id 
LEFT JOIN districts d ON e.iddistrito = d.id 
LEFT JOIN niveles cat ON e.id_categoria = cat.id 
LEFT JOIN format f ON e.id = f.id_establecimiento 
LEFT JOIN format_i fi ON e.id = fi.id_establecimiento  
LEFT JOIN format_i_one fio ON fi.id = fio.id_format_i
LEFT JOIN format_i_two fit ON fio.id = fit.id_format_i_one
LEFT JOIN format_i_files fif ON fi.id = fif.id_format_i AND fif.tipo = 1 
LEFT JOIN profesion pr ON f.id_profesion_registrador = pr.id 
LEFT JOIN condicion_profesional cp ON f.id_condicion_profesional = cp.id
LEFT JOIN regimen_laboral rl ON f.id_regimen_laboral = rl.id

WHERE LPAD(e.codigo, 8, '0') COLLATE utf8mb4_unicode_ci = LPAD(@codigo_buscado, 8, '0') COLLATE utf8mb4_unicode_ci
GROUP BY 
    e.id, i.nombre, e.nombre_eess, r.nombre, p.nombre, d.nombre, e.nombre_red, e.nombre_microred, e.nivel_atencion,
    cat.nombre, e.resolucion_categoria, e.clasificacion, e.tipo, e.codigo_ue, e.unidad_ejecutora, e.director_medico,
    e.horario, e.telefono, e.inicio_funcionamiento, e.fecha_registro, e.ultima_recategorizacion, e.antiguedad_anios,
    e.categoria_inicial, e.quintil, e.pcm_zona, e.frontera, e.numero_camas, e.autoridad_sanitaria, e.propietario_ruc,
    e.propietario_razon_social, e.situacion_estado, e.situacion_condicion, e.direccion, e.referencia, 
    e.coordenada_utm_norte, e.coordenada_utm_este, f.seguridad_hospitalaria, f.seguridad_resultado, f.seguridad_fecha,
    f.patrimonio_cultural, f.fecha_emision, f.numero_documento, f.tipo_documento_registrador, f.doc_entidad_registrador,
    f.nombre_registrador, pr.nombre, f.cargo_registrador, cp.nombre, rl.nombre, f.regimen_laboral_otro, f.email_registrador,
    f.movil_registrador, fi.t_estado_saneado, fi.t_condicion_saneamiento, fi.t_nro_contrato, fi.t_titulo_a_favor, 
    fi.t_observacion, fi.t_area_terreno, fi.t_area_construida, fi.t_area_estac, fi.t_area_libre, fi.t_estacionamiento,
    fi.t_inspeccion, fi.t_inspeccion_estado, fi.pf_ubicacion, fi.pf_estructuras, fi.pf_ins_mecanicas, fi.pf_perimetro,
    fi.pf_ins_sanitarias, fi.pf_ins_comunic, fi.pf_arquitectura, fi.pf_ins_electricas, fi.pf_distribuicion, fi.pd_ubicacion,
    fi.pd_perimetro, fi.pd_arquitectura, fi.pd_estructuras, fi.pd_ins_sanitarias, fi.pd_ins_electricas, fi.pd_ins_mecanicas,
    fi.pd_ins_comunic, fi.pd_distribuicion, fi.ae_pavimentos, fi.ae_pavimentos_nombre, fi.ae_pav_estado, fi.ae_veredas,
    fi.ae_veredas_nombre, fi.ae_ver_estado, fi.ae_zocalos, fi.ae_zocalos_nombre, fi.ae_zoc_estado, fi.ae_muros,
    fi.ae_muros_nombre, fi.ae_mur_estado, fi.ae_techo, fi.ae_techo_nombre, fi.ae_tec_estado, fi.sonatos, fi.pisos, fi.area,
    fi.ubicacion, fi.material, fi.material_nombre, fi.infraestructura_option_a, fi.infraestructura_valor_a, 
    fi.infraestructura_descripcion_1, fi.infraestructura_option_b, fi.infraestructura_valor_b, fi.infraestructura_descripcion_2,
    fi.infraestructura_option_c, fi.infraestructura_valor_c, fi.infraestructura_descripcion_3, fi.infraestructura_option_d,
    fi.infraestructura_valor_d, fi.infraestructura_option_e, fi.infraestructura_valor_e, fi.infraestructura_option_f,
    fi.infraestructura_valor_f, fi.infraestructura_option_g, fi.infraestructura_valor_g, fi.infraestructura_option_h,
    fi.infraestructura_valor_h, fi.infraestructura_option_i, fi.infraestructura_valor_i, fi.infraestructura_option_j,
    fi.infraestructura_valor_j, fi.infraestructura_option_k, fi.infraestructura_valor_k, fi.infraestructura_option_l,
    fi.infraestructura_valor_l, fi.infraestructura_option_m, fi.infraestructura_valor_m, fi.infraestructura_option_n,
    fi.infraestructura_valor_n, fi.infraestructura_descripcion_a, fi.infraestructura_descripcion_b, fi.infraestructura_descripcion_c,
    fi.infraestructura_descripcion_d, fi.infraestructura_descripcion_e, fi.infraestructura_descripcion_f, fi.infraestructura_descripcion_g,
    fi.infraestructura_descripcion_h, fi.infraestructura_descripcion_i, fi.infraestructura_descripcion_j, fi.infraestructura_descripcion_k,
    fi.infraestructura_descripcion_l, fi.infraestructura_descripcion_m, fi.infraestructura_descripcion_n, fi.estado_contencion,
    fi.estado_taludes, fi.cp_erco_perim, fi.cp_material, fi.cp_material_nombre, fi.cp_estado, fi.observacion, fi.fecha_evaluacion,
    fi.hora_inicio, fi.hora_final, fi.comentarios
LIMIT 0, 1000;